export default {
  name: 'voyage',
  title: 'Voyages',
  type: 'document',
  icon: () => '✈️',
  groups: [
    { name: 'contenu', title: '📝 Contenu' },
    { name: 'infos', title: '🗺️ Infos pratiques' },
    { name: 'seo', title: '🔍 SEO' },
  ],
  fields: [
    {
      name: 'title',
      title: 'Titre du voyage',
      type: 'string',
      group: 'contenu',
      validation: Rule => Rule.required().error('Le titre est obligatoire'),
    },
    {
      name: 'slug',
      title: 'URL de la page',
      type: 'slug',
      group: 'contenu',
      options: { source: 'title' },
      description: 'Généré automatiquement — ne pas modifier sans prévenir Quentin',
      validation: Rule => Rule.required(),
    },
    {
      name: 'pays',
      title: 'Pays / Destination',
      type: 'string',
      group: 'contenu',
      description: 'Ex: Argentine · Cuba · Mexique · Venezuela',
    },
    {
      name: 'image',
      title: 'Photo principale',
      type: 'image',
      group: 'contenu',
      options: { hotspot: true },
    },
    {
      name: 'description',
      title: 'Description',
      type: 'array',
      group: 'contenu',
      of: [{ type: 'block' }],
    },
    {
      name: 'periode',
      title: 'Période',
      type: 'string',
      group: 'infos',
      description: 'Ex: Novembre à mars',
    },
    {
      name: 'prix',
      title: 'Prix indicatif',
      type: 'string',
      group: 'infos',
      description: 'Ex: À partir de 3 500 € / personne',
    },
    {
      name: 'especes',
      title: 'Espèces ciblées',
      type: 'string',
      group: 'infos',
      description: 'Ex: Truite de mer, Dorado, Bonefish',
    },
    {
      name: 'seoTitle',
      title: 'Titre SEO',
      type: 'string',
      group: 'seo',
      validation: Rule => Rule.max(65).warning('Idéalement moins de 65 caractères'),
    },
    {
      name: 'seoDescription',
      title: 'Description SEO',
      type: 'text',
      rows: 3,
      group: 'seo',
      validation: Rule => Rule.max(160).warning('Idéalement moins de 160 caractères'),
    },
  ],
  preview: {
    select: { title: 'title', subtitle: 'pays', media: 'image' },
    prepare({ title, subtitle, media }) {
      return { title, subtitle: subtitle ? `✈️ ${subtitle}` : '', media }
    },
  },
}
